### ISSUE TITLE
support electron d.ts files without errors

### ISSUE THREAD

**Issue by seanzer** [jrieken/gulp-tsb#15]
I have an electron project where some files reference github-electron-main.d.ts and others reference github-electron-renderer.d.ts and when I compile with tsc, I don't get any errors. But, when I use gulp and gulp-tsb, I get:
Duplicate identifier 'export='."
Duplicate identifier 'export='."

reported once for each file. It looks like typescript's compiler supports this, but tsb somehow breaks the functionality.

**Comment by jrieken** [comment]
What version of the typescript compiler do you use when you compile manually, and in which files are the errors reported?

**Comment by klynch67** [comment]
I'm using version 1.6.2 w/support for JSX. Typescript doesn't report an error; unfortunately, expects the compilerOptions jsx member to have an integer value. See function checkJsxOpeningLikeElement in file typescriptServices.ts.

**Comment by jrieken** [comment]
@klynch67 - wrong issue?

**Comment by seanzer** [comment]
@jrieken Sorry, I take that back. I reduced the issue down to just 2 ts files and tsc does report the same errors. What I have is
A.ts:
```
/// <reference path='typings/github-electron/github-electron-main.d.ts' />
import foo = require('ipc');
console.log(foo.on);
```
B.ts:
```
/// <reference path='typings/github-electron/github-electron-renderer.d.ts' />
import foo = require('ipc');
console.log(foo.send);
```

When you try to compile those two files, the errors are reported in the d.ts files:
```
typings/github-electron/github-electron-main.d.ts(229,2): error TS2300: Duplicate identifier 'export='.
typings/github-electron/github-electron-renderer.d.ts(99,2): error TS2300: Duplicate identifier 'export='.
```

We used tsd to get the d.ts files from the DefinitelyTyped repo. I would have expected the reference path comments to be honored in this case. But it appears we need to do a two pass compile? I wonder if the TypeScript team is aware of this type of scenario..

**Comment by seanzer** [comment]
electron has renamed ipc and updated the d.ts files. I don't think this issue is in gulp-tsb.
