### ISSUE TITLE
lib.d.ts can't be found 

### ISSUE THREAD

**Issue by SofianHn** [jrieken/gulp-tsb#22]
Starting 1.8.2 I am getting an issue when running the [compile](https://github.com/Microsoft/vscode-docs/blob/master/scripts/gulpfile.common.js#L137) task for vscode-docs. 

The issue I am getting: 
```
[13:37:53] Using gulpfile c:\src\vscode-docs\gulpfile.js
[13:37:53] Starting 'build-website'...
[13:37:53] Starting 'compile'...
c:\src\vscode-docs\node_modules\gulp-tsb\node_modules\typescript\lib\typescript.
js:1302
        return path.replace(/\\/g, "/");

```

After debugging this it seems to be a result of b468f60a39323d42331bec7866dfac9c9e576eee, Typescript does not expect passing an empty string to [processRootFile](https://github.com/Microsoft/TypeScript/blob/a405afd40c284b082a389b215037ae0a55222a74/src/compiler/program.ts#L378) which breaking hell loose.

**Comment by jrieken** [comment]
Will tackle
