### ISSUE TITLE
how do i specify the location of the typescript compiler

### ISSUE THREAD

**Issue by smandava** [jrieken/gulp-tsb#27]
This might not be a bug, but I couldn't find any option to use the bundled (npm) version of the typescript compiler. it looks like it is using the typescript compiler from the path.

**Comment by jrieken** [comment]
TypeScript is consumed as peer-dependency

**Comment by smandava** [comment]
i have the peer dependency installed (1.75). and then I have a old version of tsc in my path (got put in the path by a third party app i think visual studio). 

Now when I run gulp with gulp-tsb, it is not using the peer dependency version, instead it is using the typescript from the path.
