### ISSUE TITLE
Lib needs to be updated to latest src build

### ISSUE THREAD

**Issue by klynch67** [jrieken/gulp-tsb#36]
Commit #33 fixed the problem where readFileSync returns a buffer instead of a string. This was due to not specifying the encoding option.

Although, the source file was fixed, the transpiled file in lib was not checked in.

The latest gulp-tsb npm continues to not specify the encoding option.

BTW: Why are the transpiled files in lib checked in? They should be .gitignored.

**Comment by Gheoan** [comment]
@jrieken please publish a proper release. Thank you.

**Comment by jrieken** [comment]
Sorry, that was an oversight. Published as `1.10.3`
