### ISSUE TITLE
allowJs compiler option

### ISSUE THREAD

**Issue by JELGT2011** [jrieken/gulp-tsb#38]
I'm working on a fairly large project and we want to use this gulp plugin because the other one is far too slow.  However, it looks like even with the --allowJs flag on the compiler, js files are ignored.  I've been digging through this for a while now, and changed `builder.getScriptFileNames()` to accept js files:

```typescript
getScriptFileNames(): string[] {

    const result: string[] = [];
    const defaultLibFileName = this.getDefaultLibFileName(this.getCompilationSettings());
    for (let fileName in this._snapshots) {
        if (/\.tsx?/i.test(path.extname(fileName))
            || /\.jsx?/i.test(path.extname(fileName))
            && fileName !== defaultLibFileName) {

            // only ts-files and not lib.d.ts-like files
            result.push(fileName)
        }
    }
    return result;
}
```

but now I get really strange errors by the typescript compiler:

```bash
.../project/node_modules/typescript/lib/typescript.js:48272

                throw new Error("Could not find file: '" + fileName + "'.");
```
even though that file is there (it only does this for js files).  I feel like I'm in a little over my head, so I was wondering if anyone here has any idea what's going on?

**Comment by jrieken** [comment]
+1 I make sure that I find time for this during the week

**Comment by jrieken** [comment]
fixed with https://github.com/jrieken/gulp-tsb/commit/e28375af4f7375fb79bbc4d5e0d4f9d94ddb56ab
