### ISSUE TITLE
tsconfig src files

### ISSUE THREAD

**Issue by mbana** [jrieken/gulp-tsb#41]
Hi, just wondering how you would avoid hardcoding the values in the `gulpfile.js` file, so instead of the below `compilation` would read all the files from the `tsconfig.json`? Would also be nice if I could avoid the `dest(...)` call as well somehow as this is in the config as well.

```
    var tsb = require('gulp-tsb');

    // create and keep compiler
    var compilation = tsb.create({
        target: 'es5',
        module: 'commonjs',
        declaration: false
    });

    gulp.task('build', function() {
        return gulp.src('src/**/*.ts')
            .pipe(compilation()) // <- new compilation
            .pipe(gulp.dest(''));
    });
```

**Edit:**

a. I also wonder why these gulp typescript tasks don't just simply delegate to the TypeScript compiler.
b. Is there any chance of merging into`gulp-typescript`? As the latter seems to support what I was looking for, e.g., however the `dest` is still there...

```
gulp.task('scripts', function() {
    var tsResult = tsProject.src() // instead of gulp.src(...)
        .pipe(ts(tsProject));

    return tsResult.js.pipe(gulp.dest('release'));
});
```

Thank you,

**Comment by jrieken** [comment]
+1 for exposing the files from the TypeScript project

**Comment by jrieken** [comment]
this is now supported
