### ISSUE TITLE
Typescript 2.0

### ISSUE THREAD

**Issue by AdamWillden** [jrieken/gulp-tsb#42]
Hi, have you tried running this with typescript 2.0 yet?

I have just tried but note I am a novice with typescript at the moment (I'm probably doing something wrong). I received the following error:

```js
D:\Repos\periodic\node_modules\gulp-tsb\lib\builder.js:227
                        if (!isExternalModule(service.getSourceFile(fileName_1))) {
                                                      ^

TypeError: service.getSourceFile is not a function
    at workOnNext (D:\Repos\periodic\node_modules\gulp-tsb\lib\builder.js:227:55)
    at nextTickCallbackWith0Args (node.js:453:9)
    at process._tickCallback (node.js:382:13)
```

**Comment by AdamWillden** [comment]
No idea if this is the right path or if I'm even still right but I've found this: https://github.com/Microsoft/TypeScript/pull/7584

**Comment by AdamWillden** [comment]
You've already addressed this.. https://github.com/jrieken/gulp-tsb/pull/40/commits/08b754a7e14e6eba9bb443ddb6e3c3604057adbd

must be me

**Comment by AdamWillden** [comment]
I have the right version 1.10.4 and I still have the same issue even though I can see that this was addressed before the last release was made. Any ideas @jrieken?

**Comment by AdamWillden** [comment]
If I make the change to my `node_modules` download of `gulp-tsb` it all works fine again.

**Comment by johnsoft** [comment]
I'm running into this issue as well. There hasn't been a release for a while… @jrieken can you publish? Thanks

**Comment by rockResolve** [comment]
Still not published to npm
