### ISSUE TITLE
Support for TS@next in master

### ISSUE THREAD

**Issue by heruan** [jrieken/gulp-tsb#44]
Does master (or other branches) already support the `typescript@next` branch of TS? I'm testing it and I'd like to compile with new TS@next options like `lib` with gulp-tsb.

**Comment by heruan** [comment]
Any feedback on this? TS 2.0 is about to be released, and gulp-tsb seems not to support it. There is any plan to keep gulp-tsb up-to-date with the latest TS?

**Comment by jrieken** [comment]
This will be tackled by #45

**Comment by AdamWillden** [comment]
2.0 is currently supported does this mean TS@next is? I'm having issues but I don't know if using TS@next not supported or if it's just my broken setup

**Comment by jrieken** [comment]
Closing this as we have adopted TypeScript 2.0 with the latest version of gulp-tsb
