### ISSUE TITLE
Consider using http://npmjs.org/package/prex for async coordination

### ISSUE THREAD

**Issue by rbuckton** [jrieken/gulp-tsb#46]
I noticed that `builder.ts` has a fair bit of async coordination, such as the `workOnNext` function and the `toBeEmitted`, `toBeCheckedSyntactically`, and `toBeCheckedSemantically` arrays.

I wrote [prex](https://github.com/rbuckton/prex) originally as part of an internal test framework, and used it in the F12 developer tools. I published the package recently as an opportunity to discuss several of the primitives with TC39 (such as [CancellationToken](https://www.npmjs.com/package/prex#cancellation)). The package adds a number of coordination primitives to simplify various existing patterns around asynchronous coordination, and the work is based primarily off of the thread/task coordination primitives found in .NET. 

A few examples of some of the available primitives that could be beneficial include:
- [CancellationToken](https://github.com/rbuckton/prex/blob/master/docs/cancellation.md#class-cancellationtoken)
- [CountdownEvent](https://github.com/rbuckton/prex/blob/master/docs/coordination.md#class-countdownevent)
- [Barrier](https://github.com/rbuckton/prex/blob/master/docs/coordination.md#class-barrier)

All of the primitives are built on top of, or to work with, ES6 native promises. They are especially useful when combined with async/await (available for `--target ES6` currently, and for other script targets in the next TypeScript release).

**Comment by jrieken** [comment]
Won't happen - but I acknowledge that the code is ugly... but it works ;-)
