### ISSUE TITLE
source maps create paths relative to tsb location

### ISSUE THREAD

**Issue by aeschli** [jrieken/gulp-tsb#48]
I use tsb in the gulpfile of https://github.com/Microsoft/vscode-json-languageservice and observe that the generated source mapping files all source references that are relative to the tsb folder, not to my source folder.

I think the reason is on https://github.com/jrieken/gulp-tsb/blob/master/src/index.ts#L46 where the base path for the tsconfig file is set to __dirname.
The doc says: 

> basePath A root directory to resolve relative path entries in the config.

Given that paths in tsconfigs are typically relative to the location of the tsconfig file this should be set to that.
For the case where tsconfig is passed in as an object, I suggest to use the current working dir.

**Comment by aeschli** [comment]
@jrieken FYI

**Comment by jrieken** [comment]
published as 2.0.2
