### ISSUE TITLE
tsconfig.json lib option doesn't work on windows

### ISSUE THREAD

**Issue by Zenorbi** [jrieken/gulp-tsb#50]
When I provide a "lib" field in tsconfig.json, it works as long as the OS uses slashes (/) as separator for paths. Typescript uses the `LanguageServiceHost.getDefaultLibFileName` as a way to get the location of the `lib` directory. On Windows the path will contain backslashes (\) . Typescript uses slashes internally and when it tries to get the directory from a path, it uses slash to find the last path component and failing to return the correct path.

https://github.com/jrieken/gulp-tsb/blob/114c0da84301e0a597ac81a4e4c20c6cb4333be0/src/builder.ts#L561

Typescript uses the `getDefaultLibFileName` as a backup, if `getDefaultLibLocation` is not available on the `LanguageServiceHost`. However, when Typescript gets the `LanguageServiceHost` from gulp-tsb, it wraps the object in a sort of proxy, which is missing the `getDefaultLibLocation` forward.

So a solution would be either:

1. Modify the `getDefaultLibFileName` to always return a path with slashes.
2. Implement the forwarding of `getDefaultLibLocation` in Typescript and implement the `getDefaultLibLocation` in gulp-tsb as well, using (or not) platform dependent separators.

I think number 1 should be the easiest and would also follow Typescript's way of using slashes on all platforms.

**Comment by dbaeumer** [comment]
Fixed in 2.0.3 (see #53)
