### ISSUE TITLE
gul-tsb fails with @types if tsconfig.json in sub directories

### ISSUE THREAD

**Issue by dbaeumer** [jrieken/gulp-tsb#51]
Install a workspace from the following zip file: 
[types.zip](https://github.com/jrieken/gulp-tsb/files/593308/types.zip)

- run npm install
- run gulp build

Observe: the compile fails

```
P:\mseng\VSCode\Playgrounds\bugs\types>gulp build
[14:33:15] Using gulpfile P:\mseng\VSCode\Playgrounds\bugs\types\gulpfile.js
[14:33:15] Starting 'build'...
"P:/mseng/VSCode/Playgrounds/bugs/types/src/test.ts(1,21): Cannot find module 'fs'."
[14:33:16] Finished 'build' after 491 ms
```

Open the workspace in VS Code and open test.ts. Observe: file has no compile errors.

**Comment by dbaeumer** [comment]
Running tsc -p src/tsconfig.json works without problems.

**Comment by dbaeumer** [comment]
@jrieken can you have a look. This blocks @types adoption in our vscode workspace.

**Comment by jrieken** [comment]
hm, I would assume that just works by having the correct TypeScript version as peer dependency...

**Comment by jrieken** [comment]
@dbaeumer You are not piping `node_modules/@types` into the stream/compiler. See the changes in https://github.com/jrieken/gulp-tsb/commit/018b81806de1dcfbebb128e352fbe40326f48bb7 for reference

**Comment by dbaeumer** [comment]
This is painful :-) and most people will fall over this. Should gulp tsb have an option to automatically do this.

**Comment by jrieken** [comment]
Well, this is whole idea of gulp and streams but you might wanna look at #52
