### ISSUE TITLE
Request/favor - could the code be modularized to decouple from Gulp

### ISSUE THREAD

**Issue by ORESoftware** [jrieken/gulp-tsb#61]
I would like to use this module, but without Gulp. Would it be possible to do so?

I am using TSC but want to speed it up. tsc -w is pretty fast, but the problem is I cannot hook into it to see when it's done.

So I have tried creating my own tsc compiler watcher that I can control:

https://github.com/Microsoft/TypeScript/issues/13608
https://github.com/Microsoft/TypeScript/issues/14722

But I am having problems. I could just steal your code, but don't want to use Gulp if I don't have to. Maybe you could modularize it and decouple the transpilation code from the Gulp code. Please lmk, thanks!

**Comment by ORESoftware** [comment]
Any word on this bird?

**Comment by ORESoftware** [comment]
TBH I think Gulp is sort of a POS, hopefully that doesn't offend anyone here. It's no surprise that nobody really misses Gulp when they just use Webpack for builds or Bash scripts, etc.

Back to the issue at hand.

I suppose I could just use vinyl streams, and avoid gulp, something like this:

```js
        let tsb = require('gulp-tsb');   // this doesn't import gulp TMK

	// create and keep compiler
	var compilation = tsb.create({
		target: 'es5',
		module: 'commonjs',
		declaration: false
	});

            someVinylReadStream()   // have to create my own Vinyl read stream independent of Gulp
                        .pipe(compilation()) //  your library, thank you
			.pipe(someVinylDestStream());

```

**Comment by jrieken** [comment]
Yeah, the beauty of gulp plugins is that they don't have a (runtime) dependency on gulp but are just node object streams. The Vinyl dependency is real but shouldn't be a problem. Thanks

**Comment by 0xorial** [comment]
@ORESoftware , did you find some workaround?
