### ISSUE TITLE
Don't force declarations=true

### ISSUE THREAD

**Issue by dawidgarus** [jrieken/gulp-tsb#71]
I've notice that gulp-tsb forces `declarations` compiler options to be `true`. (https://github.com/jrieken/gulp-tsb/blob/master/src/builder.ts#L68-L69)
Unfortunately, this causes a lot of errors in my app, like:
```
Parameter 'xxx' of public method from exported class has or is using private name 'xxx'.
Type parameter 'xxx' of exported function has or is using private name 'xxx'.
```
Since I don't need declarations in my project, I'm fine with them.
But fixing them all in order to migrate to gulp-tsb would be a drag.
Unless it's necessary for some internal workings, please consider not setting `declarations` to `true`.

**Comment by jrieken** [comment]
Using declaration files under the hood is what makes gulp-tsb fast. It caches those for each file and when code changes change the shape of it's declaration-file it knows to re-check depended files. It's unfortunate that not all code works with this strategy.
