### ISSUE TITLE
Tag new version (4.0.5)

### ISSUE THREAD

**Issue by vivekkj123** [jrieken/gulp-tsb#83]
Please tag the new version 4.0.5 in this github repository, which is essential for packing this module to debian....

**Comment by jrieken** [comment]
I don't understand what that means?

**Comment by vivekkj123** [comment]
I am packing a tool which is named HedgeDoc to Debian, For that this module i.e. gulp-tsb is a essential build dependency for that... For the completion of packing works, this module needs to be packaged to debian.. For that, you must need to tag the newsest npm version i.e. 4.0.5 in this upstream repo....That is what i meant...:)

**Comment by jrieken** [comment]
We have no plans to publish master to NPM because we selfhost of version 2. However, you can simply depend on this repo directly, no need for NPM
